name: Build Windows Executable

on: [push, workflow_dispatch]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      # 1. Clona tu repositorio en el servidor de compilación
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configura Python en el servidor
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. Instala PyInstaller
      - name: Install PyInstaller
        run: pip install pyinstaller

      # 4. Descarga y extrae los binarios de FFmpeg
      - name: Download and Extract FFmpeg
        run: |
          curl -L -o ffmpeg.zip https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.zip
          7z x ffmpeg.zip -o.
          
      # 5. (NUEVO PASO) Renombra la carpeta de FFmpeg para tener una ruta predecible
      - name: Rename FFmpeg directory
        run: |
          $ffmpeg_dir = Get-ChildItem -Path . -Directory -Filter "ffmpeg-*-essentials_build" | Select-Object -First 1
          if ($ffmpeg_dir) {
            Rename-Item -Path $ffmpeg_dir.FullName -NewName "ffmpeg_build"
            Write-Host "Renamed directory to ffmpeg_build"
          } else {
            Write-Host "Error: FFmpeg directory not found!"
            exit 1
          }
          
      # 6. (MODIFICADO) Ejecuta PyInstaller usando la ruta predecible
      - name: Build Executable with PyInstaller
        run: |
          pyinstaller --onefile --name video_checker `
          --add-binary "ffmpeg_build/bin/ffmpeg.exe;." `
          --add-binary "ffmpeg_build/bin/ffprobe.exe;." `
          video_checker.py

      # 7. Sube el .exe resultante como un "artefacto"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: video-checker-windows
          path: dist/video_checker.exe
